# Generated by Django 2.1.4 on 2019-02-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload_time',
        ),
    ]
