# Generated by Django 2.1.4 on 2019-02-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
