# Generated by Django 2.1.4 on 2019-02-22 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0002_remove_post_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='upload_time'),
            preserve_default=False,
        ),
    ]
