# Generated by Django 2.1.4 on 2019-02-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0003_post_upload_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upload_time',
        ),
    ]
