# Generated by Django 2.1.3 on 2018-11-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0003_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
