# Generated by Django 2.1.7 on 2019-02-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
