# Generated by Django 2.1.4 on 2019-02-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0005_auto_20190222_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upload_time',
        ),
    ]
