# Generated by Django 2.1.4 on 2019-02-22 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0006_auto_20190222_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload date'),
            preserve_default=False,
        ),
    ]
