# Generated by Django 2.1.7 on 2019-02-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0006_auto_20190225_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(auto_now=True, verbose_name='upload date'),
        ),
    ]
