# Generated by Django 2.1.3 on 2018-11-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration_date',
            field=models.DateField(verbose_name='expiration_date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateField(verbose_name='upload_date'),
        ),
    ]
